wandb_version: 1

activation:
  value: ReLU
batch_size:
  value: 64
epochs:
  value: 10
hidden_layers:
  value: 3
l2_reg:
  value: 0.5
learning_rate:
  value: 0.0001
neurons_per_layer:
  value: 128
optimizer:
  value: rmsprop
weight_init:
  value: random
