wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 32
epochs:
  value: 10
hidden_layers:
  value: 3
l2_reg:
  value: 0.0005
learning_rate:
  value: 0.001
neurons_per_layer:
  value: 128
optimizer:
  value: sgd
weight_init:
  value: Xavier
