wandb_version: 1

activation:
  value: ReLU
batch_size:
  value: 64
epochs:
  value: 15
hidden_layers:
  value: 3
l2_reg:
  value: 0.0005
learning_rate:
  value: 0.001
neurons_per_layer:
  value: 32
optimizer:
  value: momentum
weight_init:
  value: Xavier
