wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 16
epochs:
  value: 5
hidden_layers:
  value: 3
l2_reg:
  value: 0.5
learning_rate:
  value: 0.0001
neurons_per_layer:
  value: 64
optimizer:
  value: nadam
weight_init:
  value: random
