wandb_version: 1

activation:
  value: ReLU
batch_size:
  value: 16
epochs:
  value: 5
hidden_layers:
  value: 3
l2_reg:
  value: 0
learning_rate:
  value: 0.001
neurons_per_layer:
  value: 64
optimizer:
  value: sgd
weight_init:
  value: random
