wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 64
epochs:
  value: 5
hidden_layers:
  value: 5
l2_reg:
  value: 0
learning_rate:
  value: 0.0001
neurons_per_layer:
  value: 64
optimizer:
  value: rmsprop
weight_init:
  value: random
