wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 16
epochs:
  value: 5
hidden_layers:
  value: 3
l2_reg:
  value: 0.5
learning_rate:
  value: 0.001
neurons_per_layer:
  value: 128
optimizer:
  value: adam
weight_init:
  value: Xavier
