wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 64
epochs:
  value: 10
hidden_layers:
  value: 3
l2_reg:
  value: 0.5
learning_rate:
  value: 0.001
neurons_per_layer:
  value: 64
optimizer:
  value: nesterov
weight_init:
  value: random
