wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 16
epochs:
  value: 10
hidden_layers:
  value: 5
l2_reg:
  value: 0.0005
learning_rate:
  value: 0.001
neurons_per_layer:
  value: 64
optimizer:
  value: rmsprop
weight_init:
  value: random
