wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 32
epochs:
  value: 5
hidden_layers:
  value: 4
l2_reg:
  value: 0
learning_rate:
  value: 0.001
neurons_per_layer:
  value: 128
optimizer:
  value: nesterov
weight_init:
  value: random
