wandb_version: 1

activation:
  value: ReLU
batch_size:
  value: 32
epochs:
  value: 20
hidden_layers:
  value: 5
l2_reg:
  value: 0
learning_rate:
  value: 0.001
neurons_per_layer:
  value: 256
optimizer:
  value: nadam
weight_init:
  value: random
