wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 16
epochs:
  value: 20
hidden_layers:
  value: 5
l2_reg:
  value: 0.0005
learning_rate:
  value: 0.001
neurons_per_layer:
  value: 256
optimizer:
  value: adam
weight_init:
  value: Xavier
