wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 32
epochs:
  value: 15
hidden_layers:
  value: 5
l2_reg:
  value: 0.0005
learning_rate:
  value: 0.0001
neurons_per_layer:
  value: 32
optimizer:
  value: adam
weight_init:
  value: Xavier
