wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 16
epochs:
  value: 5
hidden_layers:
  value: 4
l2_reg:
  value: 0
learning_rate:
  value: 0.0001
neurons_per_layer:
  value: 64
optimizer:
  value: sgd
weight_init:
  value: Xavier
