wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 32
epochs:
  value: 15
hidden_layers:
  value: 5
l2_reg:
  value: 0.5
learning_rate:
  value: 0.001
neurons_per_layer:
  value: 32
optimizer:
  value: sgd
weight_init:
  value: Xavier
