wandb_version: 1

activation:
  value: ReLU
batch_size:
  value: 128
epochs:
  value: 5
hidden_layers:
  value: 4
l2_reg:
  value: 0.0005
learning_rate:
  value: 0.001
neurons_per_layer:
  value: 32
optimizer:
  value: rmsprop
weight_init:
  value: Xavier
