wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 64
epochs:
  value: 15
hidden_layers:
  value: 4
l2_reg:
  value: 0
learning_rate:
  value: 0.001
neurons_per_layer:
  value: 128
optimizer:
  value: adam
weight_init:
  value: Xavier
