wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 128
epochs:
  value: 10
hidden_layers:
  value: 5
l2_reg:
  value: 0.0005
learning_rate:
  value: 0.001
neurons_per_layer:
  value: 128
optimizer:
  value: adam
weight_init:
  value: Xavier
