wandb_version: 1

activation:
  value: ReLU
batch_size:
  value: 128
epochs:
  value: 5
hidden_layers:
  value: 3
l2_reg:
  value: 0.0005
learning_rate:
  value: 0.001
neurons_per_layer:
  value: 64
optimizer:
  value: adam
weight_init:
  value: Xavier
